### PR TITLE
Fix issue with use of architecture specific exception code

### PR DESCRIPTION
**Pull request by WorksButNotTested**

### CODE REVIEW

**Comment by andreafioraldi** [comment]
i'm not sure that interrupt will work

**Comment by andreafioraldi** [comment]
Instead of triggering an exception, call this function passing TARGET_SIGABRT https://github.com/AFLplusplus/qemuafl/blob/master/linux-user/signal.c#L624

Ofc remove the static

**Comment by WorksButNotTested** [comment]
> i'm not sure that interrupt will work

I have checked on armeb, aarch64, and x64 and all seem to work as expected.

**Comment by WorksButNotTested** [comment]
> Instead of triggering an exception, call this function passing TARGET_SIGABRT https://github.com/AFLplusplus/qemuafl/blob/master/linux-user/signal.c#L624
> 
> Ofc remove the static

I tried this originally before I made my first PR. Unfortunately, it seems that `stop_all_tasks` causes it to block indefinitely...
https://github.com/AFLplusplus/qemuafl/blob/d09c24cb12a7bd2326641ce57ea10be6c4d1d612/linux-user/signal.c#L637

**Comment by vanhauser-thc** [comment]
@WorksButNotTested have you tried EXCP_HLT?
@andreafioraldi are you happy with EXCP_INTERRUPT if TARGET_SIGABRT isn't working and the interrupt is producing a core?

**Comment by WorksButNotTested** [comment]
> @WorksButNotTested have you tried EXCP_HLT?
> @andreafioraldi are you happy with EXCP_INTERRUPT if TARGET_SIGABRT isn't working and the interrupt is producing a core?

EXCP_HLT isn’t handled in the switch for ARM and ends up in the default block here. https://github.com/AFLplusplus/qemuafl/blob/d09c24cb12a7bd2326641ce57ea10be6c4d1d612/linux-user/arm/cpu_loop.c#L469.

**Comment by andreafioraldi** [comment]
I think EXCP_INTERRUPT is then the way to go. Dunno if calling directly queue_signal is however correct, as target_siginfo_t maye have different fields for the different archs. Maybe you should call force_sig instead, but the you will not have the crashing addr info

**Comment by vanhauser-thc** [comment]
I compiled for ppc, mips, nios2 and sh4 at least they succeeded. not sure if runtime works but I guess they are.

s390x compilation fails but that is a different issue.

**Comment by WorksButNotTested** [comment]
> I think EXCP_INTERRUPT is then the way to go. Dunno if calling directly queue_signal is however correct, as target_siginfo_t maye have different fields for the different archs. Maybe you should call force_sig instead, but the you will not have the crashing addr info

I think we are ok to use those constants, there are similar examples for both SH4 and SPARC using similar calls to `queue_signal` here:
https://github.com/AFLplusplus/qemuafl/blob/dc19175a0bf4cf34e19944d084d92f33f26df93d/linux-user/sh4/cpu_loop.c#L68
https://github.com/AFLplusplus/qemuafl/blob/dc19175a0bf4cf34e19944d084d92f33f26df93d/linux-user/sparc/cpu_loop.c#L223

Thanks for the merge, sorry it didn't all go smoothly!

**Pull request merged**
